# Generated by Django 5.2.17 on 2026-08-30 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('chapter', models.PositiveSmallIntegerField(help_text="Chapter number in Mikele's reading app (usually id + 1).")),
                ('year', models.PositiveSmallIntegerField()),
                ('date_label', models.CharField(help_text='As printed in the book, e.g. "September 8" or "May 7 (i)".', max_length=40)),
                ('date', models.DateField(help_text='Resolved calendar date, used for the timeline angle.')),
                ('summary', models.TextField(help_text='Paraphrased summary — never a verbatim quote.')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FolkloreEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('wikipedia_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'folklore entity',
                'verbose_name_plural': 'folklore entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OuterRingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('global', 'Global'), ('italian_campaign', 'Italian campaign')], max_length=20)),
                ('note', models.TextField()),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('person_type', models.CharField(choices=[('camorrista_bandit', 'Camorrista / bandit'), ('police_official', 'Police official'), ('informant_contact', 'Informant / contact'), ('companion', 'Companion'), ('aristocrat', 'Aristocrat'), ('allied_colleague', 'Allied colleague'), ('civilian_friend', 'Civilian friend'), ('notable_civilian', 'Notable civilian')], max_length=20)),
                ('wikipedia_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('place_type', models.CharField(choices=[('street', 'Street'), ('piazza', 'Piazza'), ('landmark', 'Landmark'), ('district', 'District'), ('religious_site', 'Religious site'), ('town', 'Town'), ('region', 'Region'), ('natural_feature', 'Natural feature')], max_length=20)),
                ('wikipedia_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='EntryFolklore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='Context for this entry.', max_length=500)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naples44.entry')),
                ('folklore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naples44.folkloreentity')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='folklore',
            field=models.ManyToManyField(blank=True, related_name='entries', through='naples44.EntryFolklore', to='naples44.folkloreentity'),
        ),
        migrations.CreateModel(
            name='EntryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='Context for this entry.', max_length=400)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naples44.entry')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naples44.person')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='entries', through='naples44.EntryPerson', to='naples44.person'),
        ),
        migrations.AddField(
            model_name='entry',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='entries', to='naples44.place'),
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('note', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='naples44.entry')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='entries', to='naples44.theme'),
        ),
        migrations.AddConstraint(
            model_name='entryfolklore',
            constraint=models.UniqueConstraint(fields=('entry', 'folklore'), name='uniq_entry_folklore'),
        ),
        migrations.AddConstraint(
            model_name='entryperson',
            constraint=models.UniqueConstraint(fields=('entry', 'person'), name='uniq_entry_person'),
        ),
    ]
