# Generated by Django 5.2.17, then hand-edited to populate slugs before the
# unique constraint is applied.

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    for model_name in ("Place", "Person", "FolkloreEntity"):
        Model = apps.get_model("naples44", model_name)
        seen = set()
        for obj in Model.objects.all().order_by("pk"):
            base = slugify(obj.name)[:130] or "item"
            slug = base
            n = 2
            while slug in seen:
                slug = f"{base}-{n}"
                n += 1
            seen.add(slug)
            obj.slug = slug
            obj.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("naples44", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="folkloreentity",
            name="description",
            field=models.TextField(blank=True, help_text="Shown on the entity's page. Optional."),
        ),
        migrations.AddField(
            model_name="person",
            name="description",
            field=models.TextField(blank=True, help_text="Shown on the person's page. Optional."),
        ),
        migrations.AddField(
            model_name="place",
            name="description",
            field=models.TextField(blank=True, help_text="Shown on the place's page. Optional."),
        ),
        # 1. add slug WITHOUT the unique constraint
        migrations.AddField(
            model_name="folkloreentity",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=140),
            preserve_default=False,
        ),
        # 2. fill them in
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # 3. now enforce uniqueness
        migrations.AlterField(
            model_name="folkloreentity",
            name="slug",
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="slug",
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="slug",
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name="folkloreentity",
            name="wikipedia_url",
            field=models.URLField(blank=True, help_text="Further reading — linked only from the entity's own page."),
        ),
        migrations.AlterField(
            model_name="person",
            name="wikipedia_url",
            field=models.URLField(blank=True, help_text="Further reading — linked only from the person's own page."),
        ),
        migrations.AlterField(
            model_name="place",
            name="wikipedia_url",
            field=models.URLField(blank=True, help_text="Further reading — linked only from the place's own page."),
        ),
    ]
