# Generated by Django 5.2.17 on 2026-08-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naples44', '0002_folkloreentity_description_folkloreentity_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='geocode_source',
            field=models.CharField(blank=True, help_text='Where latitude/longitude came from (wikipedia, nominatim, manual).', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
