# Generated by Django 5.2.17 on 2026-09-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naples44', '0003_place_geocode_source_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='book_role',
            field=models.TextField(blank=True, help_text="How the place figures in Naples '44 — hand-written, never auto-seeded."),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, help_text='What / where the place is. Seedable from Wikipedia via `manage.py seed_place_descriptions`.'),
        ),
    ]
