# Generated by Django 5.2.17 on 2026-09-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naples44', '0004_place_book_role_alter_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='folkloreentity',
            name='book_role',
            field=models.TextField(blank=True, help_text="How it figures in Naples '44 — hand-written, never auto-seeded."),
        ),
        migrations.AddField(
            model_name='person',
            name='book_role',
            field=models.TextField(blank=True, help_text="How they figure in Naples '44 — hand-written, never auto-seeded."),
        ),
        migrations.AlterField(
            model_name='folkloreentity',
            name='description',
            field=models.TextField(blank=True, help_text='What the saint / feast / custom is. Seedable from Wikipedia via `manage.py seed_wikipedia_descriptions` where an article exists.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, help_text='Who they are / were. Seedable from Wikipedia via `manage.py seed_wikipedia_descriptions` where an article exists.'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, help_text='What / where the place is. Seedable from Wikipedia via `manage.py seed_wikipedia_descriptions`.'),
        ),
    ]
