#!/usr/bin/env bash
#
# Backup DB data to a portable JSON fixture.
# This, not db.sqlite3 itself, is the portability mechanism for this pattern.

DIR_DB_BACKUP="backups/django"

echo -e "\nBACKING UP DB DATA ....src/manage.py dumpdata TO /$DIR_DB_BACKUP"
echo "+++++++++++++++++"

FILENAME="$DIR_DB_BACKUP/dump.json"
src/manage.py dumpdata \
    --exclude auth.permission --exclude contenttypes --exclude sessions --exclude admin.logentry \
    --indent=2 -o $FILENAME

echo -e "\nDONE: $FILENAME\n"
