#!/usr/bin/env bash
#
# Load DB data from a JSON fixture (see tools/db-dump).

echo "================="
echo "LOAD DATA FROM LOCAL JSON DUMP"
echo "Please pass a JSON file in backups/ and ensure DB is initialised and empty"
echo "================="

src/manage.py loaddata $1

echo "DONE"
